{"uuid": "4201d5a9-70c5-4272-86a8-4e7ab2362a98", "children": ["2ec840e5-fa9c-4fb1-a8cd-4da6aba19c4d"], "befores": [{"name": "caserun", "status": "passed", "start": 1545915586587, "stop": 1545915586587}], "afters": [{"name": "caserun::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8201\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 836, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/tmh/PycharmProjects/appauto/base/conftest_android.py\", line 73, in caserun\n    action.sleep(1).get_img(\"用例结束前的截图\")\n  File \"/Users/tmh/PycharmProjects/appauto/base/action.py\", line 44, in get_img\n    png_data=self.driver.get_screenshot_as_png()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 1064, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 1074, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1545915612038, "stop": 1545915613069}], "start": 1545915586587, "stop": 1545915613069}