{"uuid": "9a26726e-ed6e-4c4e-bff1-93d11cc8c11a", "children": ["01564dfd-c599-49c9-9835-644f9325d5bb"], "befores": [{"name": "suitinit", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.jm.android.jumei' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.jm.android.jumei.home.activity.NewHomeActivity' or 'com.jm.android.jumei.com.jm.android.jumei.home.activity.NewHomeActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 969, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 828, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/tmh/PycharmProjects/appauto/tests/test_usercenter/conftest.py\", line 24, in suitinit\n    p.特卖首页.pageinto(action)\n  File \"/Users/tmh/PycharmProjects/appauto/lib/pages/productpage.py\", line 27, in pageinto\n    action.start_activity(self.activity)\n  File \"/Users/tmh/PycharmProjects/appauto/base/action.py\", line 54, in start_activity\n    self.driver.start_activity(self.env.appium.get(\"appPackage\"), app_activity, **opts)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/webdriver.py\", line 981, in start_activity\n    self.execute(Command.START_ACTIVITY, data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1545393997296, "stop": 1545394026844}], "start": 1545393997296, "stop": 1545394027038}